# Generated by Django 3.2.5 on 2022-02-04 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=20, verbose_name='city')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=50, verbose_name='org_name')),
                ('desc', models.TextField(verbose_name='description')),
                ('tag', models.CharField(default='Well-known', max_length=10, verbose_name='tag')),
                ('category', models.CharField(choices=[('pxjg', 'Orgnization'), ('gr', 'Personal'), ('gx', 'University')], default='pxjg', max_length=4, verbose_name='org_category')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_number')),
                ('image', models.ImageField(upload_to='Org/%Y/%m', verbose_name='Logo')),
                ('student', models.IntegerField(default=0, verbose_name='student_number')),
                ('course_nums', models.IntegerField(default=0, verbose_name='course_numbers')),
            ],
            options={
                'verbose_name': 'Class Orgnization',
                'verbose_name_plural': 'Class Orgnization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=20, verbose_name='Teacher')),
                ('work_years', models.IntegerField(default=0, verbose_name='work_years')),
                ('work_company', models.CharField(max_length=50, verbose_name='work_company')),
                ('work_position', models.CharField(max_length=50, verbose_name='work_position')),
                ('points', models.CharField(max_length=50, verbose_name='teaching_points')),
                ('age', models.IntegerField(default=18, verbose_name='age')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_number')),
                ('image', models.ImageField(upload_to='Teacher/%Y/%m', verbose_name='image')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgnizations.courseorg', verbose_name='Orgnizations')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
