# Generated by Django 3.2.5 on 2022-02-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnizations', '0002_auto_20220204_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='orgnizations.city', verbose_name='city'),
        ),
    ]
