# Generated by Django 3.2.5 on 2022-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnizations', '0003_courseorg_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='address',
            field=models.CharField(default='', max_length=80, verbose_name='address'),
        ),
    ]
