# Generated by Django 3.2.5 on 2022-02-04 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgnizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=50, verbose_name='Class_Name')),
                ('desc', models.CharField(max_length=300, verbose_name='Class_Description')),
                ('learn_time', models.IntegerField(default=0, verbose_name='learn_time(min)')),
                ('degree', models.CharField(choices=[('cj', 'low'), ('zj', 'medium'), ('gj', 'high')], max_length=10, verbose_name='degree')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite_number')),
                ('click_nums', models.IntegerField(default=0, verbose_name='click_number')),
                ('category', models.CharField(default='Backend', max_length=20, verbose_name='class_category')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='class_tag')),
                ('youneed_know', models.CharField(default='', max_length=300, verbose_name='need_know')),
                ('techer_tell', models.CharField(default='', max_length=300, verbose_name='teacher_tell_you')),
                ('detail', models.TextField(verbose_name='class_detail')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='tag_image')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgnizations.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Class Information',
                'verbose_name_plural': 'Class Information',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=100, verbose_name='Chapter_name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learn_time(min)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Chapter_Information',
                'verbose_name_plural': 'Chapter_Information',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=100, verbose_name='Video_name')),
                ('learn_times', models.IntegerField(default=0, verbose_name='Learn_time(min)')),
                ('url', models.CharField(max_length=200, verbose_name='url_address')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Chapter_Information',
                'verbose_name_plural': 'Chapter_Information',
            },
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='download_address')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'class_resources',
                'verbose_name_plural': 'class_resources',
            },
        ),
    ]
