# Generated by Django 3.2.5 on 2022-02-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnizations', '0005_auto_20220205_0628'),
        ('courses', '0002_auto_20220204_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgnizations.courseorg', verbose_name='course_org'),
        ),
    ]
