# Generated by Django 3.2.5 on 2022-02-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_classics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_classics',
            field=models.BooleanField(default=True, verbose_name='classicornot'),
        ),
    ]
